global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'magentic-core'
    static_configs:
      - targets: ['magentic-core:8081']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'voice-backend'
    static_configs:
      - targets: ['voice-backend:8765']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  - job_name: 'valkey'
    static_configs:
      - targets: ['valkey:6379']
    scrape_interval: 30s
